Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning

DatabaseOptions:
  Host: 192.168.1.115
  Port: 5432
  Database: outbox
  Username: postgres
  Password: postgres

SenderOptions:
  Server: "192.168.1.115:9092"
  ClientId: outbox

GraylogOptions:
  Host: 192.168.1.115
  Port: 12201

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Warning
      System: Warning