Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
    
DatabaseOptions:
  Host: localhost
  Port: 5555
  Database: outbox
  Username: postgres
  Password: postgres
  
SenderOptions:
  Server: "localhost:9092"
  ClientId: outbox